dotnet build ControllerViewDataParserLibrary
dotnet build DataGeneratorLibrary
dotnet build DataStorageLibrary
dotnet build FileWriterLibrary
dotnet build MethodScriptGenerator
dotnet build PageObjectGeneratorLibrary
dotnet build ScenarioGeneratorLibrary
dotnet build TestScriptBuilderLibrary
